apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Overlay staging : iso-prod côté operators, ressources dimensionnées pour tests de charge.
namespace: openshift-gitops
resources:
  - ../../apps/socle


