# Red Hat Build of Keycloak (RHBK) — Operator #4 du socle
# IdP OIDC pour l'IUN. Le CR Keycloak sera ajouté en phase 2 (configuration realm).
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: rhbk-operator
spec:
  channel: stable-v26
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace


