apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iun-opencrvs-dev
resources:
  - 01-imagestream-buildconfig.yaml
  - 02-deployment.yaml
  - 03-service.yaml
  - 04-networkpolicy-egress-openimis.yaml
