apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-imagestream-buildconfig.yaml
  - 02-deployment.yaml
  - 03-service.yaml
  - 04-networkpolicy-egress-uin.yaml
  - 05-networkpolicy-ingress-mosip-side.yaml
