# OpenShift Service Mesh 3 (Istio upstream) — Operator #3 du socle
# OSSM 3 = Istio sans Kiali Operator embarqué (à installer séparément si besoin).
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace


