---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socle-openshift-pipelines
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: iun-platform
  source:
    repoURL: https://github.com/enguser-1/iun-gitops.git
    targetRevision: HEAD
    path: components/openshift-pipelines/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true


