---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socle-cloudnative-pg
  namespace: iun-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: iun-platform
  source:
    repoURL: https://github.com/enguser-1/iun-gitops.git
    targetRevision: HEAD
    path: components/cloudnative-pg/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
